# Generated by Django 2.2.12 on 2024-04-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
